apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangodeployment
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-container
        image: pamblo/django-app:v2
        ports:
        - containerPort: 8000
